# Generated by Django 4.1 on 2024-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_booked_car_alter_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
