# Generated by Django 4.1 on 2024-02-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cars_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
