# Generated by Django 4.1 on 2024-02-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Client', 'Client')], max_length=10),
        ),
    ]
