# Generated by Django 4.1 on 2024-02-20 12:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cars_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Cars.get_unique_filename),
        ),
    ]
