# Generated by Django 4.1 on 2024-02-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cars_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='booked_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='expire_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
