# Generated by Django 4.1 on 2024-02-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cars_booked_time_alter_cars_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBookingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='booked_time',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='expire_time',
        ),
        migrations.AddField(
            model_name='cars',
            name='bookedDateList',
            field=models.ManyToManyField(to='api.carbookingdate'),
        ),
    ]
