# Generated by Django 4.1 on 2024-02-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_carbookingdate_remove_cars_booked_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='bookedDateList',
        ),
        migrations.AddField(
            model_name='carbookingdate',
            name='car_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cars'),
        ),
    ]
