# Generated by Django 4.1 on 2024-02-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_cars_booker_carbookingdate_booker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbookingdate',
            old_name='booker',
            new_name='booker_id',
        ),
    ]
