# Generated by Django 4.1 on 2024-02-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_booker_carbookingdate_booker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbookingdate',
            name='booking_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
